spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.mashibing.entity

# 指定logger日志对象的日志级别
logging:
  level:
    com:
      mashibing:
        mapper: debug
